# Generated by Django 3.1.3 on 2020-11-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.CharField(blank=True, choices=[('Door', 'door'), ('Garage', 'garage'), ('Window', 'window'), ('Light', 'light')], max_length=10),
        ),
    ]
