# Generated by Django 3.1.3 on 2020-11-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(blank=True, choices=[('door', 'Door'), ('garage', 'Garage'), ('window', 'Window'), ('light', 'Light')], max_length=10),
        ),
    ]
