# Generated by Django 3.1.3 on 2020-11-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auto_20201127_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(blank=True, choices=[('Door', 'Door'), ('Garage', 'Garage'), ('Window', 'Window'), ('Light', 'Light')], max_length=10),
        ),
    ]
